language: python
sudo: required
python:
    - "2.7"
services:
    - postgresql
    - redis-server
install:
    - pip install -r dev-requirements.txt
    - bash bin/travis-build.bash
    
script: sh bin/travis-run.sh
deploy:
    username: "$PYPI_USER"
    password: "$PYPI_PASSWORD"
    distributions: "sdist bdist_wheel"
    on:
      python: 2.7
      tags: true
