language: python
sudo: required
python:
    - "2.7"
services:
    - postgresql
    - redis-server
install:
    - bash bin/travis-build.bash
    - pip install dev-requirements
script: sh bin/travis-run.sh
